### ISSUE TITLE
C13 Footprint

### ISSUE THREAD

**Issue by Asnivor** [EmberHeavyIndustries/HID2AMI#1]
Hi there,

So the 1.1.0 BOM lists C3 & C13 as 1206 10uF, but the footprint for C13 looks the same as the other 0805 caps:

![image](https://user-images.githubusercontent.com/7911038/69045609-19a07000-09ef-11ea-889a-66edc42f7ab8.png)

Should C13 be a 0805 10uF, or should it be an 0805 100nF like the other caps?

Thanks!

-Asni

**Comment by EmberHeavyIndustries** [comment]
Hello Asni, sorry for my late response. You spotted it right: it is a little design "bug" I did not fix among revisions. I did not notice it because I never assembled neither C3 nor C13 (they are absolutely optional, needed just in case your Amiga had a very unstable power supply circuit only). In any case, if you want to assemble them, you can safely use 0805 caps for both. Thank you for noticing me, anyway.
