### ISSUE TITLE
Firmware Sources

### ISSUE THREAD

**Issue by maximevince** [EmberHeavyIndustries/HID2AMI#4]
Hi @EmberHeavyIndustries,

Awesome project, but I cannot seem to find the firmware source code anywhere.
Is it close-source, or is it just me that can't find it anywhere?

Thanks for the project(s)!

Cheers,
Maxime

**Comment by EmberHeavyIndustries** [comment]
Hello Maxime,

I released open hardware schematics, but reserved the firmware code closed, because of too many scammers who stoled some of  my open source projects in the past, making money over my work.

I understand it could be unwise with respect to honest users (which are the most), but that's it.

If you build up the adapter, you can ask me for a (signed) copy of the firmware executable at any time.

Cheers,

**Comment by maximevince** [comment]
Hi,

It took me some time, but I've build a couple of these adapters now (for my own use).
Could you send me the firmware image? (My email is in my GitHub profile, I couldn't find yours)

Thanks

**Comment by EmberHeavyIndustries** [comment]
Hello, sent you an email with instructions !
